### ISSUE TITLE
Issue enabling webhook.

### ISSUE THREAD

**Issue by XenoUniv3rse** [donetick/donetick#140]
Clicking on the text box to enter the webhook address just disabled webhook again. Clicking on the save button also disabled webhook

**Comment by luke3579** [comment]
I found I had to click on the checkmark to enable webhook, then press tab to select the box and paste in my url.
My issue is donetick isn’t sending reminders via webhooks, I’m getting skipped and completed tasks but no due reminders

**Comment by XenoUniv3rse** [comment]
ahhh yea that worked thanks. It also sucks that notifications are not sent via webhooks

**Comment by meauxt** [comment]
this should be fixed in [v0.1.36](https://github.com/donetick/donetick/releases/tag/v0.1.36 )

**Comment by XenoUniv3rse** [comment]
@meauxt perfect, thank you

**Comment by glombek** [comment]
I'm running v0.1.36 but still seeing the issue where notification webhooks are not sending.

I've seen a `thing` change notification work fine.

Logs show:

```
2025-03-03T21:58:25.381Z	debug	service/planner.go:69	Generated notificationscount1

2025-03-03T21:59:55.449Z	debug	notifier/scheduler.go:92	Scheduler running  NOTIFICATION_SCHEDULER  time2025-03-03 21:59:55.449212105 +0000 UTC m=+180.161937370

2025-03-03T21:59:55.450Z	debug	notifier/scheduler.go:65	Getting pending notifications count 1

2025-03-03T21:59:55.474Z	debug	notifier/scheduler.go:103	Scheduler job completed NOTIFICATION_SCHEDULER  time: 25.397024ms
```
