### ISSUE TITLE
Circle Problems

### ISSUE THREAD

**Issue by holycow131415** [donetick/donetick#243]
Hello,

I love the potential of this app! It seems like there are circle issues. I am self hosting on Truenas Community.

In settings, the Copy Circle ID  and Copy Circle URL buttons don't do anything, The Circle text box is too small too, it did not display my admin's full Circle ID. I had to go into the SQLite DB to find it to be able to add my other user (userB) into the Circle. Now since this userB is in my circle, I made it an Admin...

However, when I make new chores, it will eventually bug out and not allow this userB to edit the chore. It appears to start bugging out when I try to change the assignment from userB to userA (the original admin account). The userA account is still able to edit the chore.
```
`Save Failed

Failed to save chore, please try again.`
```

Another issue is userB can not view labels and probably "things" too (havent used it yet) that userA has created.

I think this web app needs a real user management section to create accounts and give permissions to accounts to be able to view/modify chores, labels, things etc.

**Comment by teunbruijnen** [comment]
I'm self hosting on truenas scale and also get the same save failed error when a user in a circle tries to edit a task that I created.
However I can edit tasks created by other users without error.

**Comment by hoborm** [comment]
Can you confirm it's fixed in the latest release please?
If not please provide logs to the issue.

**Comment by holycow131415** [comment]
Copy Code and Copy link in Circle Settings still do not put anything into my clipboard. This doesnt make any logs.

UserA created a chore, UserB can't delete it
UserB created a chore, UserA can't delete it.

Both are circle admins.

`2026-01-31 19:45:21.190681+00:002026/01/31 14:45:21 [32m/home/runner/work/donetick/donetick/internal/chore/repo/repository.go:47 [33mSLOW SQL >= 200ms
2026-01-31 19:45:21.190690+00:00[0m[31;1m[222.592ms] [33m[rows:1][35m INSERT INTO `chores` (`name`,`frequency_type`,`frequency`,`frequency_meta`,`frequency_meta_v2`,`next_due_date`,`is_rolling`,`assigned_to`,`assign_strategy`,`is_active`,`notification`,`notification_meta`,`notification_meta_v2`,`labels`,`circle_id`,`created_at`,`updated_at`,`created_by`,`updated_by`,`status`,`priority`,`completion_window`,`points`,`description`,`require_approval`,`is_private`,`deadline_offset`) VALUES ("test linda","once",1,NULL,"{}",NULL,false,1,"least_completed",true,false,NULL,"{}",NULL,1,"2026-01-31 19:45:20.967","2026-01-31 14:45:20.967",2,2,0,0,NULL,NULL,"",false,false,NULL) RETURNING `id`[0m
2026-01-31 19:46:19.035418+00:002026-01-31T19:46:19.035418508Z
2026-01-31 19:46:19.035553+00:002026/01/31 14:46:19 [31;1m/home/runner/work/donetick/donetick/internal/chore/repo/repository.go:127 [35;1mrecord not found
2026-01-31 19:46:19.035593+00:00[0m[33m[0.532ms] [34;1m[rows:0][0m SELECT * FROM `chores` WHERE id = 11 AND created_by = 1 ORDER BY `chores`.`id` LIMIT 1
2026-01-31 19:46:50.657308+00:002026-01-31T19:46:50.657308133Z
2026-01-31 19:46:50.657343+00:002026/01/31 14:46:50 [31;1m/home/runner/work/donetick/donetick/internal/chore/repo/repository.go:127 [35;1mrecord not found
`

Labels still can't be seen by each other.

**Comment by hoborm** [comment]
Do they make any requests in your "network" tab from your browser?

**Comment by holycow131415** [comment]
I dont know what this means or for which issue you are asking about. I use Firefox btw.

**Comment by hoborm** [comment]
I will look into the issue, are you on [v0.1.64](https://github.com/donetick/donetick/releases/tag/v0.1.64) ?

**Comment by holycow131415** [comment]
Yes, I am using donetick/donetick:latest

**Comment by hoborm** [comment]
Are you using HTTPS or simple HTTP? Browser security is disabling the clipboard access if the communication is not encrypted. (signed certificate)

**Comment by holycow131415** [comment]
I believe just http. I was only testing and playing around in the app so I did not set it up behind nginx.

**Comment by hoborm** [comment]
> I believe just http. I was only testing and playing around in the app so I did not set it up behind nginx.

That is the issue I belive.
