### ISSUE TITLE
Unable to update your profile. Please check your connection and try again.

### ISSUE THREAD

**Issue by thecoffeebin** [donetick/donetick#305]
First off this is an amazing app, it is not complicated like all other to-do apps but also packed with essential features.

I'm selfhosting this app and it's a pleasure to use.

However there're still some bugs that need to squash in order for us to start enjoying this app.

One of them is the upload issue (profile avatar or attachments), right now the profile avatar can be uploaded to S3 but whenever I'm trying to save, it gives this error (same experience on official site: donetick.com)

<img width="665" height="77" alt="Image" src="https://github.com/user-attachments/assets/82da5fd6-4e3a-4eb2-838a-30933b4be7b6" />

I hope the author of this app keep improving this app because it has so much potential!

Thank you!

**Comment by thecoffeebin** [comment]
FYI this issue persists even after updated to the latest relase v0.1.57 / v0.1.110 (not sure why the version does not tally between release and displayed by webapp).

It prompts the error whenever I click on "Save" under Profile Settings. Obviously the changes (Profile photo, name etc) were not saved.

**Comment by jlar0che** [comment]
I'm having the same issue on version 0.1.110

**Comment by perseveration** [comment]
Also having this issue - latest version, updated minutes ago.

**Comment by thecoffeebin** [comment]
I see the latest version can be deployed from docker(hub) is still 0.1.57

**Comment by perseveration** [comment]
Docker hub is showing 0.1.59 for me, updated 7hrs ago.

**Comment by thecoffeebin** [comment]
> Docker hub is showing 0.1.59 for me, updated 7hrs ago.

You're right. Now I see the tag for 0.1.59 but after upgrading to it still the same error and I'm unable to save profile. Seems weird this basic feature is still not fixed.

**Comment by gajazura** [comment]
Facing the same issue, Being a new user I thought I might have setup something wrong.

**Comment by lxne** [comment]
Same for me. Uploading a picture to a task doesn't work either 'File too large' (even if it is tiny).

**Comment by thecoffeebin** [comment]
I fixed it with the help of https://github.com/donetick/donetick/issues/230 -> installing the tzdata package into the Docker image

Did it this way and works for me

(docker-compose.yml) add:
```
command: /bin/sh -c "apk add --no-cache tzdata && ./donetick"
```

Voila! Hope this helps others who face the same issue.

**Comment by lxne** [comment]
> 
> ```
> command: /bin/sh -c "apk add --no-cache tzdata && ./donetick"
> ```

This does not fix the upload issue I am having.
I still cannot upload a profile picture.

What this did fix: I now can change my name in the profile.

**Comment by TheBToby** [comment]
> ```
> command: /bin/sh -c "apk add --no-cache tzdata && ./donetick"
> ```

This did not resolve the issue for me either. I still get the error in the container log:
```
MissingRegion: could not find region configuration
```
