### ISSUE TITLE
Task won't trigger on Thing state

### ISSUE THREAD

**Issue by twillist** [donetick/donetick#347]
I'm trying to get a task to trigger based on a thing boolean but when I change the boolean to the desired state nothing happens. No logs either

**Comment by thegiogi** [comment]
Can confirm the same behaviour.

**Comment by hesspoint** [comment]
Same here. I have a Boolean thing as trigger. I change it to true in Home Assistant and nothing happens

**Comment by clb92** [comment]
I'm having this problem too, I think.

I have a boolean to keep track of whether the dishwasher is clean or dirty, and it doesn't reliably cause my two chores (Empty the dishwasher / Fill and start the dishwasher) to show up as due.

**Comment by chrishas35** [comment]
I am able to flip the trigger in the WebUI (V0.1.115) and the task reliably appears. However, I want the assignment to Round Robin and that does not seem to be taking as it always assigns to the same person.

**Comment by taraldb** [comment]
When i flip the task with API it doesn't trigger, but if I do it from the webui it triggers.
Running V0.1.115 (API: 0.1.64)

Logs did not show anything meaningful for the period where thing boolean was flipped.

**Comment by koolmon10** [comment]
I was having this issue, but updating to the latest version fixed it

**Comment by Ian-Hartwell** [comment]
Ive just come across this problem, 

V0.1.115 (API: 0.1.64)

Home Assistant config:
```
  donetick_set_thing_value:
    url: "http://XXXXX:2021/eapi/v1/things/{{ thing_id }}/state?state={{ thing_value | lower }}"
    method: GET
    headers:
      secretkey: !secret donetick_token
```

The value does get updated, but doesnt trigger chore

**Comment by meauxt** [comment]
I think this should be fixed as of 0.1.70 release . If not please let.me know and feel free to reopen

**Comment by chrishas35** [comment]
Just updated to 0.1.74 and this part is still a problem for me:

> I am able to flip the trigger in the WebUI (V0.1.115) and the task reliably appears. However, I want the assignment to Round Robin and that does not seem to be taking as it always assigns to the same person.

I am now triggering via Home Assistant. I am seeing the following in logs upon completing the fired task:

```
server-1  | 2026/02/15 23:42:40 /home/runner/work/donetick/donetick/internal/chore/repo/repository.go:281 record not found
server-1  | [0.635ms] [rows:0] SELECT * FROM `chore_histories` WHERE chore_id = ? AND status = ?  ORDER BY `chore_histories`.`id` LIMIT 1
```

If I go into Archived, and view history I see the triggered task's history of completion.

@meauxt I lack permission to reopen. If you'd rather a new issue, happy to do so.

**Comment by kareem613** [comment]
It worked for me. 
Note. Changing the state view developer tools didn't. Flipping the helper in the integration view (devices and services->donetick) did. I'm not sure how that's not the same thing though.

**Comment by meauxt** [comment]
@chrishas35 okay then, ifthat'st the cause, if we can open a new issue would be best, and I can take a look at it!
